version: '3'

services:

  app:
    build: .
    container_name: service-videos
  #  entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3003:3003
      - 3000:3000
      - 8080:8080
    volumes:
      - .:/home/node/app